### ISSUE TITLE
can not run aldex2 in qiime2

### ISSUE THREAD

**Issue by tomaseagan** [mortonjt/q2-aldex2#13]
I have tried to install and run Aldex2, following the tutorial. Regardless of R versions, (I have 4.0.0) I get this error message when I try to run ALDEx2 (see below)

Any help is much appreciated!

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  meta = meta.loc[list(table.index)]
Running external command line application(s). This may print messages to stdout and/or stderr.
The command(s) being run are below. These commands cannot be manually re-run as they will depend on temporary files that no longer exist.

Command: run_aldex2.R /var/folders/m8/j3znyy6x3vg_pn_8gzycm5fr0000gn/T/tmp3ylq_tyr/input.tsv.biom /var/folders/m8/j3znyy6x3vg_pn_8gzycm5fr0000gn/T/tmp3ylq_tyr/input.map.txt freq_exac_0_vs_1 128 t all /var/folders/m8/j3znyy6x3vg_pn_8gzycm5fr0000gn/T/tmp3ylq_tyr/output.summary.txt

R version 3.5.1 (2018-07-02) 
Error in library(ALDEx2) : there is no package called ‘ALDEx2’
Execution halted
Traceback (most recent call last):
  File "/Users/tomasmikaleagan/miniconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/q2_aldex2/_method.py", line 59, in aldex2
    run_commands([cmd])
  File "/Users/tomasmikaleagan/miniconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/q2_aldex2/_method.py", line 21, in run_commands
    subprocess.run(cmd, check=True)
  File "/Users/tomasmikaleagan/miniconda3/envs/qiime2-2020.2/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['run_aldex2.R', '/var/folders/m8/j3znyy6x3vg_pn_8gzycm5fr0000gn/T/tmp3ylq_tyr/input.tsv.biom', '/var/folders/m8/j3znyy6x3vg_pn_8gzycm5fr0000gn/T/tmp3ylq_tyr/input.map.txt', 'freq_exac_0_vs_1', '128', 't', 'all', '/var/folders/m8/j3znyy6x3vg_pn_8gzycm5fr0000gn/T/tmp3ylq_tyr/output.summary.txt']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tomasmikaleagan/miniconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/q2cli/commands.py", line 328, in __call__
    results = action(**arguments)
  File "</Users/tomasmikaleagan/miniconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/decorator.py:decorator-gen-477>", line 2, in aldex2
  File "/Users/tomasmikaleagan/miniconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/Users/tomasmikaleagan/miniconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/Users/tomasmikaleagan/miniconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/q2_aldex2/_method.py", line 63, in aldex2
    " and stderr to learn more." % e.returncode)
Exception: An error was encountered while running ALDEx2 in R (return code 1), please inspect stdout and stderr to learn more.

**Comment by dgiguer** [comment]
Hi @tomaseagan, 

From this information:

```
R version 3.5.1 (2018-07-02)
Error in library(ALDEx2) : there is no package called ‘ALDEx2’
Execution halted
```

My guess is that you have multiple versions of R installed, it appears that `qiime` is calling 3.5.1 and not finding `ALDEx2`. My guess is `ALDEx2` is installed in your R 4.0 library? In any case, make sure that the R version in your `qiime` environment has `ALDEx2` installed! 

Dan

**Comment by tomaseagan** [comment]
That ws correct, however R 3.5.1 comes with the QIIME installation. After several error messages I did manage to install the package in R 3.5.1 (I don't remember the details now, but one was that one of the dependencies of ALDEx2 was made for R 3-6.x I think), and then run it in QIIME :-) Thanks your your help!

**Comment by elcega** [comment]
@tomaseagan  How did you solve this? I think I might have the same problem as I have Aldex2 installed in R but seems like my qiime is not detecting it...>
