### ISSUE TITLE
Plugin error from aldex2

### ISSUE THREAD

**Issue by KeLi1018** [mortonjt/q2-aldex2#18]
Hi!
I have tried to install and run Aldex2, following the tutorial. But an error was encountered while running ALDEx2 in R (return code 1).
Version: qiime2-2019.7

It really puzzled me. Please, help me to figure it out! Thanks!
And here is the log file:
```
Running external command line application(s). This may print messages to stdout and/or stderr.
The command(s) being run are below. These commands cannot be manually re-run as they will depend on temporary files that no longer exist.

Command: run_aldex2.R /tmp/tmp7cblrvmt/input.tsv.biom /tmp/tmp7cblrvmt/input.map.txt group 128 t all /tmp/tmp7cblrvmt/output.summary.txt

R version 3.5.1 (2018-07-02) 
[1] "aldex.clr: generating Monte-Carlo instances and clr values"
[1] "operating in serial mode"
[1] "computing center with all features"
[1] "aldex.ttest: doing t-test"
Error in aldex.ttest(x, conditions, paired.test = FALSE) : 
  only two condition levels are currently supported
Calls: aldex -> aldex.ttest
Traceback (most recent call last):
  File "/home/tianxuekai/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2_aldex2/_method.py", line 59, in aldex2
    run_commands([cmd])
  File "/home/tianxuekai/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2_aldex2/_method.py", line 21, in run_commands
    subprocess.run(cmd, check=True)
  File "/home/tianxuekai/miniconda3/envs/qiime2-2019.7/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['run_aldex2.R', '/tmp/tmp7cblrvmt/input.tsv.biom', '/tmp/tmp7cblrvmt/input.map.txt', 'group', '128', 't', 'all', '/tmp/tmp7cblrvmt/output.summary.txt']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tianxuekai/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2cli/commands.py", line 327, in __call__
    results = action(**arguments)
  File "</home/tianxuekai/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/decorator.py:decorator-gen-481>", line 2, in aldex2
  File "/home/tianxuekai/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 240, in bound_callable
    output_types, provenance)
  File "/home/tianxuekai/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 383, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/tianxuekai/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2_aldex2/_method.py", line 63, in aldex2
    " and stderr to learn more." % e.returncode)
Exception: An error was encountered while running ALDEx2 in R (return code 1), please inspect stdout and stderr to learn more.
```

**Comment by colinvwood** [comment]
This seems to be occurring because there is no check for samples that may exist in the table artifact but not in the metadata. The input to the R script then has three categories, (in this case: 'MOR', 'VEH', and blank/missing) thus the "only two condition levels are currently supported" error message.

See [here](https://forum.qiime2.org/t/aldex2-error-only-two-condition-levels-are-currently-supported/25890).
